module.exports = {
    1: {
        id: 1,
        name: 'Poke Ball',
        searchName: 'pokeball',
        plural: 'Poke Balls',
        emoji: '<:pokeball:793190053954060318>',
        description: 'A tool used for catching Pokemon.',
        shopItem: true,
        price: 100,
        sellPrice: 50,
        fromPokestop: true,
    },
    2: {
        id: 1,
        name: 'Great Ball',
        searchName: 'greatball',
        plural: 'Great Balls',
        emoji: '<:greatball:793190054003998720>',
        description: 'An improved ball for catching Pokemon.',
        shopItem: true,
        price: 200,
        sellPrice: 100,
        fromPokestop: true,
    },
    3: {
        id: 3,
        name: 'Ultra Ball',
        searchName: 'ultraball',
        plural: 'Ultra Balls',
        emoji: '<:ultraball:793190053957992488>',
        description: 'A greatly improved ball for catching Pokemon.',
        shopItem: true,
        price: 500,
        sellPrice: 250,
        fromPokestop: true,
    },
    4: {
        id: 4,
        name: 'Potion',
        searchName: 'potion',
        plural: 'Potions',
        emoji: '<:potion:793189202404966440>',
        description: 'Heals a Pokemon for 20 HP.',
        shopItem: true,
        price: 50,
        sellPrice: 25,
        fromPokestop: true,
    },
}